language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mengzhou44/travis-ex  -f Dockerfile.dev .

script:
  - docker run -e CI=true mengzhou44/travis-ex  npm run test
